In [1]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix


from sklearn.feature_extraction.text import CountVectorizer
import re
from sklearn import preprocessing
import scipy
from sklearn.model_selection import GridSearchCV
import sklearn
from sklearn.decomposition import PCA
from sklearn.preprocessing import OneHotEncoder
import time
import pickle
import copy

In [3]:
feature_matrix = pd.read_csv("jobs_feature.csv")
feature_matrixindustry_Accounting

,telecommuting,has_company_logo,has_questions,fraudulent,company_profile_length,description_length,requirements_length,benefits_length,industry_Accounting,industry_Airlines/Aviation,...,function._Public Relations,function._Purchasing,function._Quality Assurance,function._Research,function._Sales,function._Science,function._Strategy/Planning,function._Supply Chain,function._Training,function._Writing/Editing
0,0,1,0,0,2559,871,1383,100,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,1,1,0,829,391,88,16,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,1,1,0,1251,724,805,2047,0,0,...,0,0,1,0,0,0,0,0,0,0
3,0,1,0,0,829,838,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,1,0,0,92,35,17,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5357,0,0,0,1,0,421,651,10,0,0,...,0,0,0,0,0,0,0,0,0,0
5358,0,0,0,1,0,874,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5359,0,0,1,1,0,336,35,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5360,0,1,1,1,1099,930,418,2198,0,0,...,0,0,0,0,0,0,0,0,0,0
5361,0,0,0,1,0,536,221,153,0,0,...,0,0,0,0,0,0,0,0,0,0

In [7]:
feature_matrix[feature_matrix['industry_Accounting']==1]

,telecommuting,has_company_logo,has_questions,fraudulent,company_profile_length,description_length,requirements_length,benefits_length,industry_Accounting,industry_Airlines/Aviation,...,function._Public Relations,function._Purchasing,function._Quality Assurance,function._Research,function._Sales,function._Science,function._Strategy/Planning,function._Supply Chain,function._Training,function._Writing/Editing
115,0,0,0,0,228,1610,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
462,0,0,0,0,228,1196,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
532,0,0,0,0,228,899,1288,0,1,0,...,0,0,0,0,0,0,0,0,0,0
568,0,1,1,0,829,656,70,17,1,0,...,0,0,0,0,0,0,0,0,0,0
743,0,0,0,0,0,117,6,6,1,0,...,0,0,0,0,0,0,0,0,0,0
809,0,0,0,0,228,1170,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
845,0,0,0,0,228,1168,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
868,0,1,1,0,532,1126,589,0,1,0,...,0,0,0,0,0,0,0,0,0,0
899,0,0,0,0,228,1408,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
1398,0,1,1,0,1708,2093,1161,1033,1,0,...,0,0,0,0,0,0,0,0,0,0
1483,1,1,0,0,573,4868,1694,0,1,0,...,0,0,0,0,0,0,0,0,0,0
1589,0,1,1,0,820,764,414,360,1,0,...,0,0,0,0,0,0,0,0,0,0
1753,0,1,1,0,720,1212,306,154,1,0,...,0,0,0,0,0,0,0,0,0,0
2133,0,1,0,0,1251,1621,961,0,1,0,...,0,0,0,0,0,0,0,0,0,0
2157,0,1,0,0,550,2141,953,0,1,0,...,0,0,0,0,0,0,0,0,0,0
2210,0,1,1,0,452,2377,769,0,1,0,...,0,0,0,0,0,0,0,0,0,0
2470,0,1,0,0,699,1918,4516,591,1,0,...,0,0,0,0,0,0,0,0,0,0
2747,0,0,0,0,228,1400,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
2810,0,1,0,0,554,1067,1067,0,1,0,...,0,0,0,0,0,0,0,0,0,0
2983,0,1,1,0,657,667,1140,0,1,0,...,0,0,0,0,0,0,0,0,0,0
3023,0,0,0,0,0,938,0,88,1,0,...,0,0,0,0,0,0,0,0,0,0
3298,0,0,0,0,228,1210,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
3439,0,0,1,0,0,2729,599,137,1,0,...,0,0,0,0,0,0,0,0,0,0
3559,0,1,1,0,567,526,178,0,1,0,...,0,0,0,0,0,0,0,0,0,0
3606,0,0,0,0,228,1170,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
3758,0,0,0,0,228,1160,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
3970,0,1,1,0,233,205,90,0,1,0,...,0,0,0,0,0,0,0,0,0,0
4144,0,0,0,0,228,1419,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
4544,0,1,0,0,1251,1771,734,1990,1,0,...,0,0,0,0,0,0,0,0,0,0
4549,0,1,1,0,1708,1109,467,439,1,0,...,0,0,0,0,0,0,0,0,0,0
4738,0,0,0,0,228,1410,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
4849,0,0,0,0,228,1803,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
4910,0,0,0,0,0,1076,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
5104,0,0,1,1,0,1783,229,250,1,0,...,0,0,0,0,0,0,0,0,0,0
5112,0,0,0,1,0,598,323,158,1,0,...,0,0,0,0,0,0,0,0,0,0
5152,0,1,0,1,351,209,1652,0,1,0,...,0,0,0,0,0,0,0,0,0,0
5159,0,0,0,1,0,501,160,520,1,0,...,0,0,0,0,0,0,0,0,0,0
5160,0,0,0,1,0,455,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
5161,0,0,0,1,0,1034,458,32,1,0,...,0,0,0,0,0,0,0,0,0,0
5165,0,0,0,1,0,251,49,47,1,0,...,0,0,0,0,0,0,0,0,0,0
5171,0,1,0,1,917,1357,506,76,1,0,...,0,0,0,0,0,0,0,0,0,0
5172,0,0,0,1,0,501,160,520,1,0,...,0,0,0,0,0,0,0,0,0,0
5193,0,0,0,1,0,175,0,15,1,0,...,0,0,0,0,0,0,0,0,0,0
5215,0,0,0,1,0,902,561,138,1,0,...,0,0,0,0,0,0,0,0,0,0
5223,0,1,0,1,351,209,1652,0,1,0,...,0,0,0,0,0,0,0,0,0,0
5252,0,0,0,1,0,412,465,131,1,0,...,0,0,0,0,0,0,0,0,0,0
5257,0,0,0,1,0,929,160,520,1,0,...,0,0,0,0,0,0,0,0,0,0
5274,0,0,0,1,0,1511,480,0,1,0,...,0,0,0,0,0,0,0,0,0,0
5292,0,0,0,1,0,769,319,197,1,0,...,0,0,0,0,0,0,0,0,0,0
5299,0,0,0,1,0,1311,199,139,1,0,...,0,0,0,0,0,0,0,0,0,0
5307,0,1,1,1,1016,1441,555,0,1,0,...,0,0,0,0,0,0,0,0,0,0

In [10]:
X = feature_matrix.drop(['fraudulent', 'company_profile_length', 'description_length', 'requirements_length', 'benefits_length'], axis=1)
y = feature_matrix['fraudulent']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3,random_state=42)

In [11]:
rfm = RandomForestClassifier(n_estimators = 200, random_state=9)
rfm.fit(X_train,y_train)

0.9864108713029577

In [47]:
y_pred_rfm = rfm.predict(X_test)
y_test = np.array(y_test)
print(len(y_test)) # number of test samples
wrong_index = np.where(y_pred_rfm != y_test)
wrong_index

1609

(array([ 153,  171,  218,  232,  308,  332,  343,  388,  390,  409,  426,
         432,  470,  489,  509,  535,  579,  583,  616,  648,  718,  719,
         737,  786,  789,  847,  865,  872,  912,  958,  998, 1036, 1082,
        1127, 1224, 1300, 1322, 1335, 1339, 1358, 1418, 1419, 1452, 1478,
        1606], dtype=int64),)

In [48]:
pred_prob = rfm.predict_proba(X_test)
print(pred_prob[wrong_index, :])
print(y_test[wrong_index])

[[[0.81       0.19      ]
  [0.92854167 0.07145833]
  [0.90741531 0.09258469]
  [0.91485714 0.08514286]
  [0.76253592 0.23746408]
  [0.29       0.71      ]
  [0.76253592 0.23746408]
  [0.87850995 0.12149005]
  [0.97135024 0.02864976]
  [0.76253592 0.23746408]
  [0.93708333 0.06291667]
  [0.84354167 0.15645833]
  [0.92091071 0.07908929]
  [0.29112798 0.70887202]
  [0.76253592 0.23746408]
  [0.76253592 0.23746408]
  [0.97135024 0.02864976]
  [0.89921622 0.10078378]
  [1.         0.        ]
  [0.9896875  0.0103125 ]
  [0.68       0.32      ]
  [0.86       0.14      ]
  [0.90741531 0.09258469]
  [0.671      0.329     ]
  [0.975      0.025     ]
  [0.995      0.005     ]
  [0.94481481 0.05518519]
  [0.985      0.015     ]
  [0.96617584 0.03382416]
  [0.83302098 0.16697902]
  [0.925      0.075     ]
  [0.76253592 0.23746408]
  [0.995      0.005     ]
  [0.92       0.08      ]
  [0.29112798 0.70887202]
  [0.29112798 0.70887202]
  [0.90741531 0.09258469]
  [1.         0.        ]
  [0.995      0.005     ]
  [0.74806533 0.25193467]
  [0.865      0.135     ]
  [0.76253592 0.23746408]
  [0.97135024 0.02864976]
  [0.83427951 0.16572049]
  [1.         0.        ]]]
[1 1 1 1 1 0 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 1
 1 1 1 1 1 1 1 1]

In [53]:
#We should look at sensitivity instead!!!!!!
confusion_matrix(y_true=y_test, y_pred=y_pred_rfm)
# the (i,j)-entry is equal to the number of observations known to be in group i and
# predicted to be in group j
# TPR = entry (2,2) / sum of bottom row

array([[1539,    4],
       [  41,   25]], dtype=int64)

In [54]:
# try ROC curve to determine threshold probability

Help on function confusion_matrix in module sklearn.metrics._classification:

confusion_matrix(y_true, y_pred, *, labels=None, sample_weight=None, normalize=None)
    Compute confusion matrix to evaluate the accuracy of a classification.

    By definition a confusion matrix :math:`C` is such that :math:`C_{i, j}`
    is equal to the number of observations known to be in group :math:`i` and
    predicted to be in group :math:`j`.

    Thus in binary classification, the count of true negatives is
    :math:`C_{0,0}`, false negatives is :math:`C_{1,0}`, true positives is
    :math:`C_{1,1}` and false positives is :math:`C_{0,1}`.

    Read more in the :ref:`User Guide <confusion_matrix>`.

    Parameters
    ----------
    y_true : array-like of shape (n_samples,)
        Ground truth (correct) target values.

    y_pred : array-like of shape (n_samples,)
        Estimated targets as returned by a classifier.

    labels : array-like of shape (n_classes), default=None
        List of labels to index the matrix. This may be used to reorder
        or select a subset of labels.
        If ``None`` is given, those that appear at least once
        in ``y_true`` or ``y_pred`` are used in sorted order.

    sample_weight : array-like of shape (n_samples,), default=None
        Sample weights.

        .. versionadded:: 0.18

    normalize : {'true', 'pred', 'all'}, default=None
        Normalizes confusion matrix over the true (rows), predicted (columns)
        conditions or all the population. If None, confusion matrix will not be
        normalized.

    Returns
    -------
    C : ndarray of shape (n_classes, n_classes)
        Confusion matrix whose i-th row and j-th
        column entry indicates the number of
        samples with true label being i-th class
        and predicted label being j-th class.

    See Also
    --------
    plot_confusion_matrix : Plot Confusion Matrix.
    ConfusionMatrixDisplay : Confusion Matrix visualization.

    References
    ----------
    .. [1] `Wikipedia entry for the Confusion matrix
           <https://en.wikipedia.org/wiki/Confusion_matrix>`_
           (Wikipedia and other references may use a different
           convention for axes).

    Examples
    --------
    >>> from sklearn.metrics import confusion_matrix
    >>> y_true = [2, 0, 2, 2, 0, 1]
    >>> y_pred = [0, 0, 2, 2, 0, 2]
    >>> confusion_matrix(y_true, y_pred)
    array([[2, 0, 0],
           [0, 0, 1],
           [1, 0, 2]])

    >>> y_true = ["cat", "ant", "cat", "cat", "ant", "bird"]
    >>> y_pred = ["ant", "ant", "cat", "cat", "ant", "cat"]
    >>> confusion_matrix(y_true, y_pred, labels=["ant", "bird", "cat"])
    array([[2, 0, 0],
           [0, 0, 1],
           [1, 0, 2]])

    In the binary case, we can extract true positives, etc as follows:

    >>> tn, fp, fn, tp = confusion_matrix([0, 1, 0, 1], [1, 1, 1, 0]).ravel()
    >>> (tn, fp, fn, tp)
    (0, 2, 1, 1)

In [2]:
# Sean's parsing function

def parsing(dat,train_dat):
    
    ### SALARY PROCESSING 
    # see if character is in text
    def alpha_in_text(text):
        return(any(c.isalpha() for c in text))

    # see how many dashes are in text
    def number_of_dashes(text):
        return(sum([1 for i in text if '-' in i]))

    # extract smallest salary range value
    def salary_extract_first(text):

        if pd.isna(text) is True:
            return(-1)

        elif alpha_in_text(text) is True:
            return(-2)

        elif '-' in text:
            if number_of_dashes(text) == 1:
                if re.split('-',text)[0].isdigit() is True:
                    return(float(re.split('-',text)[0]))
                else:
                    return(-1)

            else:
                return(-1)
        else:
            return(-1)

    # largest salary range value
    def salary_extract_second(text):

        if pd.isna(text) is True:
            return(-1)

        elif alpha_in_text(text) is True:
            return(-2)

        elif '-' in text:
            if number_of_dashes(text) == 1:
                if re.split('-',text)[1].isdigit() is True:
                    return(float(re.split('-',text)[1]))
                else:
                    return(-1)

            else:
                return(-1)
        else:
            return(-1)

    # convert numeric salary to category
    def salary_category_first(number):
        percentile = [60.0, 14000.0, 20000.0, 30000.0, 35000.0, 44374.4, 55000.0, 70000.0, 90000.0]
        if number == -1:
            return(str(1))

        if number == -2:
            return(str(2))

        for i in range(len(percentile)):
            if i not in {0,8}:
                if (number > percentile[i-1]) & (number <= percentile[i]):
                    return(str(i+3))
                else:
                    continue

            if i == 0:
                if number < percentile[0]:
                    return(str(i+3))
            if i == 8:
                if number >= percentile[8]:
                    return(str(i+3))



    def salary_category_second(number):
        percentile = [120, 20000.0, 30000.0, 40000.0, 50000.0, 65000.0, 80000.0, 100000.0, 130000.0]
        if number == -1:
            return(str(1))

        if number == -2:
            return(str(2))

        for i in range(len(percentile)):
            if i not in {0,8}:
                if (number > percentile[i-1]) & (number <= percentile[i]):
                    return(str(i+3))
                else:
                    continue

            if i == 0:
                if number < percentile[0]:
                    return(str(i+3))
            if i == 8:
                if number >= percentile[8]:
                    return(str(i+3))
    
    
    ### ONE HOT ENCODING (training)
    employment_type_onehot = OneHotEncoder(handle_unknown='ignore').fit(train_dat[['employment_type']].fillna('NaN'))
    required_experience_onehot = OneHotEncoder(handle_unknown='ignore').fit(train_dat[['required_experience']].fillna('NaN'))
    required_education_onehot = OneHotEncoder(handle_unknown='ignore').fit(train_dat[['required_education']].fillna('NaN'))
    industry_onehot = OneHotEncoder(handle_unknown='ignore').fit(train_dat[['industry']].fillna('NaN'))
    function_onehot = OneHotEncoder(handle_unknown='ignore').fit(train_dat[['function.']].fillna('NaN'))
    category_1 = train_dat.salary_range.apply(salary_extract_first).apply(salary_category_first)
    category_2 = train_dat.salary_range.apply(salary_extract_second).apply(salary_category_second)
    salary_1_onehot = OneHotEncoder(handle_unknown='ignore').fit(pd.DataFrame(category_1))
    salary_2_onehot = OneHotEncoder(handle_unknown='ignore').fit(pd.DataFrame(category_2))
    
    ### OTHER PARSING
    nacols = dat.isna()[['title', 'location', 'department', 'salary_range','description', 'requirements', 'benefits',
                      'telecommuting', 'has_company_logo', 'has_questions', 'employment_type',
                      'required_experience', 'required_education', 'industry', 'function.']].astype('int')
    
    numeric_cols = dat[['telecommuting', 'has_company_logo', 'has_questions']]
    # func to count words in document
    document_word_count = lambda document: len(document.split(' '))
    
    # count words in column
    columns = ["company_profile","description","requirements","benefits"]
    df = copy.deepcopy(dat[columns])
    for column in columns:
            df[(str(column) + "_length")] = dat[column].apply(lambda x: len(x) if x == x else 0)
    
    
    # salary column one hot
    category_1 = dat.salary_range.apply(salary_extract_first).apply(salary_category_first)
    category_2 = dat.salary_range.apply(salary_extract_second).apply(salary_category_second)
    
    salary_1_transform = pd.DataFrame.sparse.from_spmatrix(salary_1_onehot.transform(pd.DataFrame(category_1)))
    salary_2_transform = pd.DataFrame.sparse.from_spmatrix(salary_2_onehot.transform(pd.DataFrame(category_2)))
    
    # transform to one hot
    employment_type_transformed =  pd.DataFrame.sparse.from_spmatrix(employment_type_onehot.transform(dat[['employment_type']].fillna('NaN')))
    required_experience_transformed =  pd.DataFrame.sparse.from_spmatrix(required_experience_onehot.transform(dat[['required_experience']].fillna('NaN')))
    required_education_transformed =  pd.DataFrame.sparse.from_spmatrix(required_education_onehot.transform(dat[['required_education']].fillna('NaN')))
    industry_transformed =  pd.DataFrame.sparse.from_spmatrix(industry_onehot.transform(dat[['industry']].fillna('NaN')))
    function_transformed =  pd.DataFrame.sparse.from_spmatrix(function_onehot.transform(dat[['function.']].fillna('NaN')))
    
    
    return(pd.concat([nacols,salary_1_transform, salary_2_transform,df.iloc[:,4:],
                      employment_type_transformed, required_experience_transformed, required_education_transformed, industry_transformed,function_transformed,numeric_cols],axis = 1))

In [3]:
dat_train = pd.read_csv("job_training_data.csv")
data = parsing(dat_train,dat_train)

In [6]:
X = data
y = dat_train['fraudulent']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state=42)

C:\Users\user\anaconda3\lib\site-packages\sklearn\utils\validation.py:515: UserWarning: pandas.DataFrame with sparse columns found.It will be converted to a dense numpy array.
  warnings.warn(
C:\Users\user\anaconda3\lib\site-packages\sklearn\utils\validation.py:515: UserWarning: pandas.DataFrame with sparse columns found.It will be converted to a dense numpy array.
  warnings.warn(

array([[1535,    8],
       [  34,   32]], dtype=int64)

,title,location,department,salary_range,description,requirements,benefits,telecommuting,has_company_logo,has_questions,...,31,32,33,34,35,36,37,telecommuting,has_company_logo,has_questions
0,0,0,1,1,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0
1,0,0,1,1,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,1
2,0,0,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,1
3,0,0,1,1,0,1,1,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0
4,0,0,1,1,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5357,0,0,1,1,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0
5358,0,0,1,1,0,1,1,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0
5359,0,0,0,1,0,0,1,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,1
5360,0,0,0,1,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,1
5361,0,0,1,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0

In [10]:
rf = RandomForestClassifier(n_estimators = 200,max_features=None ,n_jobs=6, random_state=11)
rf.fit(X_train,y_train)
sklearn.metrics.confusion_matrix(y_test, rf.predict(X_test))

C:\Users\user\anaconda3\lib\site-packages\sklearn\utils\validation.py:515: UserWarning: pandas.DataFrame with sparse columns found.It will be converted to a dense numpy array.
  warnings.warn(
C:\Users\user\anaconda3\lib\site-packages\sklearn\utils\validation.py:515: UserWarning: pandas.DataFrame with sparse columns found.It will be converted to a dense numpy array.
  warnings.warn(

array([[1535,    8],
       [  33,   33]], dtype=int64)

In [28]:
pred = (rf.predict_proba(X_test)[:, 1] > 0.1).astype(int) # classify as fraudulent if prob of fraud > threshold
sklearn.metrics.confusion_matrix(y_test, pred)

C:\Users\user\anaconda3\lib\site-packages\sklearn\utils\validation.py:515: UserWarning: pandas.DataFrame with sparse columns found.It will be converted to a dense numpy array.
  warnings.warn(

array([[1413,  130],
       [  19,   47]], dtype=int64)

In [31]:
def recall(confusion_mat):
    c10 = confusion_mat[1,0]
    c11 = confusion_mat[1,1]
    return c11 / (c10 + c11)

def precision(confusion_mat):
    c00 = confusion_mat[0,0]
    c01 = confusion_mat[0,1]
    c10 = confusion_mat[1,0]
    c11 = confusion_mat[1,1]
    return (c00 + c11) / (c00 + c01 + c10 + c11)

In [34]:
threshold = np.array([.5,.4,.3,.2,.15,.1,.07,.05]) # trying different thresholds
recall_rate = np.zeros(len(threshold))
precision_rate = np.zeros(len(threshold))

for i in range(len(threshold)):
    pred = (rf.predict_proba(X_test)[:, 1] > threshold[i]).astype(int) # classify as fraudulent if prob of fraud > threshold
    confusion_matrix = sklearn.metrics.confusion_matrix(y_test, pred)
    
    recall_rate[i] = recall(confusion_matrix)
    precision_rate[i] = precision(confusion_matrix)

C:\Users\user\anaconda3\lib\site-packages\sklearn\utils\validation.py:515: UserWarning: pandas.DataFrame with sparse columns found.It will be converted to a dense numpy array.
  warnings.warn(
C:\Users\user\anaconda3\lib\site-packages\sklearn\utils\validation.py:515: UserWarning: pandas.DataFrame with sparse columns found.It will be converted to a dense numpy array.
  warnings.warn(
C:\Users\user\anaconda3\lib\site-packages\sklearn\utils\validation.py:515: UserWarning: pandas.DataFrame with sparse columns found.It will be converted to a dense numpy array.
  warnings.warn(
C:\Users\user\anaconda3\lib\site-packages\sklearn\utils\validation.py:515: UserWarning: pandas.DataFrame with sparse columns found.It will be converted to a dense numpy array.
  warnings.warn(
C:\Users\user\anaconda3\lib\site-packages\sklearn\utils\validation.py:515: UserWarning: pandas.DataFrame with sparse columns found.It will be converted to a dense numpy array.
  warnings.warn(
C:\Users\user\anaconda3\lib\site-packages\sklearn\utils\validation.py:515: UserWarning: pandas.DataFrame with sparse columns found.It will be converted to a dense numpy array.
  warnings.warn(
C:\Users\user\anaconda3\lib\site-packages\sklearn\utils\validation.py:515: UserWarning: pandas.DataFrame with sparse columns found.It will be converted to a dense numpy array.
  warnings.warn(
C:\Users\user\anaconda3\lib\site-packages\sklearn\utils\validation.py:515: UserWarning: pandas.DataFrame with sparse columns found.It will be converted to a dense numpy array.
  warnings.warn(

array([0.97451833, 0.97016781, 0.96395277, 0.94530764, 0.93349907,
       0.9073959 , 0.88812927, 0.86451212])

In [35]:
print(recall_rate)
print(precision_rate)

[0.5        0.53030303 0.57575758 0.60606061 0.66666667 0.71212121
 0.75757576 0.75757576]
[0.97451833 0.97016781 0.96395277 0.94530764 0.93349907 0.9073959
 0.88812927 0.86451212]